language: python
python:
- '2.7'
sudo: false
before_install:
- nvm install stable
install:
- pip install -U pip setuptools>=18.5
- pip install pygments cssselect html5lib lxml
- git clone --depth=500 --branch=master https://github.com/tabatkins/bikeshed.git ./bikeshed
- pushd ./bikeshed
#- git checkout fbf1456a756299b3ff6d248d0857ec87f2e68cd7
- popd
- pip install --editable ./bikeshed
- bikeshed update
# Use cached copy of bikeshed data files to give consistent builds
#- cp -R .spec-data/* ./bikeshed/bikeshed/spec-data
script: bikeshed spec
env:
  global:
  - ENCRYPTION_LABEL: "de967aecadce"
  - COMMIT_AUTHOR_EMAIL: "plh+deploy@w3.org"

deploy:
  provider: script
  skip_cleanup: true
  script:
    - ./.multipage-split.sh
    - ./.deploy-output.sh
  on:
    branch: master