language: python
python:
- '2.7'
sudo: false
branches:
  only:
  - master
before_install:
- chmod 755 ./.deploy-output.sh
- chmod 755 ./.multipage-split.sh
- nvm install stable
install:
- pip install -U pip setuptools>=18.5
- pip install pygments cssselect html5lib lxml
- git clone --depth=150 --branch=master https://github.com/tabatkins/bikeshed.git ./bikeshed
# Use stable copy of bikeshed
- pushd ./bikeshed
- git checkout 9260eac3642631ba07cbb9e9b2936efe928153e3
- popd
- pip install --editable ./bikeshed
# Use cached copy of bikeshed data files to give consistent builds
#- bikeshed update
- cp -R .spec-data/* ./bikeshed/bikeshed/spec-data
script: 'bikeshed spec && ./.multipage-split.sh'
after_success:
- './.deploy-output.sh'
env:
  global:
  - ENCRYPTION_LABEL: "de967aecadce"
  - COMMIT_AUTHOR_EMAIL: "plh+deploy@w3.org"
